# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
  - main: main.go promblem.go http.go
    binary: leetcode-cli
    env:
    - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
#dockers:
#  - goos: linux
#    goarch: amd64
#    binaries:
#      - leetcode-cli
#    skip_push: false
#    dockerfile: Dockerfile
#    image_templates:
#      - quay.io/helmpack/chart-releaser:{{ .Tag }}
#      - quay.io/helmpack/chart-releaser:latest
#    build_flag_templates:
#      - --label=org.label-schema.schema-version=1.0
#      - --label=org.label-schema.version={{ .Version }}
#      - --label=org.label-schema.name={{ .ProjectName }}
#      - --label=org.label-schema.build-date={{ .Date }}
#      - --label=org.label-schema.description='cr - The chart release tool'
#      - --label=org.label-schema.vendor=Helm
