# Golang CircleCI 2.1 configuration file
version: 2.1

orbs:
  # See https://circleci.com/orbs/registry/orb/circleci/go.
  go: circleci/go@0.2.0

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
    working_directory: /go/src/github.com/yeya24/leetcode-go
    steps:
      - checkout
      - go/load-cache
      - run: go mod tidy
      - run:
          name: test
          command: |
            go vet ./...
            go test ./tests
      - go/save-cache

  release:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
    working_directory: /go/src/leetcode-go
    steps:
      - checkout
      - go/load-cache
      - run: curl -sL https://git.io/goreleaser | bash
      - go/save-cache

  publish-images:
    docker:
      - image: circleci/golang:1.12
    environment:
      - GO111MODULE: "on"
    working_directory: /go/src/leetcode-go
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export VERSION=${CIRCLE_TAG:1}' >> $BASH_ENV
      - go/load-cache
      - run:
          name: build
          command: go build -o leetcode-cli .
      - run:
          name: push images
          command: |
            docker build -t yeya24/leetcode-cli:$VERSION .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push yeya24/leetcode-cli:$VERSION
      - go/save-cache

workflows:
  version: 2
  ci:
    jobs:
      - test
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - publish-images:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/